// Generated from docs/canonical-system/system-registry.json. Do not edit.
const PROOF_RECEIPT_SYSTEM_IDS: &[&str] = &[
    "visible-radiance-interface-event",
    "universe-identity",
    "field-basis",
    "stellar-orbital",
    "geological-atmospheric",
    "hydrological-state",
    "climate-state",
    "surface-material-state",
    "regional-environment-state",
    "physical-region-partition",
    "physical-path-substrate",
    "visible-radiance-bulk-transfer",
    "derived-world-rules",
    "lazy-universe-hierarchy",
    "world-history-ledger",
    "significance-system",
    "streaming-scheduler",
    "semantic-emergence",
    "construction-language",
    "organism-ecology",
    "aesthetic-grammar",
    "representation-selector",
    "asset-factory",
    "procedural-animation",
];
