param([switch]$Check)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$boundaries = Get-Content (Join-Path $root 'governance\module-boundaries.json') -Raw | ConvertFrom-Json
$contexts = Get-Content (Join-Path $root 'governance\module-context-registry.json') -Raw | ConvertFrom-Json
if ($boundaries.schema_version -ne 1 -or $contexts.schema_version -ne 1) {
  throw 'Unsupported module boundary or context registry schema.'
}
& (Join-Path $PSScriptRoot 'verify-modularity.ps1')
& (Join-Path $PSScriptRoot 'refresh-proof-receipt-system-ids.ps1') -Check:$Check

$boundaryById = @{}; foreach ($module in $boundaries.modules) { $boundaryById[$module.id] = $module }
$contextById = @{}; foreach ($module in $contexts.modules) {
  if ($contextById.ContainsKey($module.id)) { throw "Duplicate module context: $($module.id)" }
  $contextById[$module.id] = $module
}
$boundaryIds = @($boundaryById.Keys | Sort-Object)
$contextIds = @($contextById.Keys | Sort-Object)
if (($boundaryIds -join "`n") -ne ($contextIds -join "`n")) {
  throw "Module context coverage differs from declared boundaries.`nDeclared: $($boundaryIds -join ', ')`nContext: $($contextIds -join ', ')"
}

function Get-SourceFingerprint([string]$moduleRoot) {
  $files = @(Get-ChildItem -LiteralPath $moduleRoot -Recurse -Force -File | Where-Object {
    $_.Name -ne 'MODULE.md' -and $_.FullName -notmatch '[\\/](?:target|node_modules|dist|gen)[\\/]'
  } | Sort-Object FullName)
  $lines = foreach ($file in $files) {
    $relative = $file.FullName.Substring($moduleRoot.Length).TrimStart('\','/').Replace('\','/')
    "${relative}:$((Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant())"
  }
  $bytes = [Text.Encoding]::UTF8.GetBytes(($lines -join "`n"))
  $sha = [Security.Cryptography.SHA256]::Create()
  try { return ([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-', '').ToLowerInvariant() }
  finally { $sha.Dispose() }
}

function Add-List([Text.StringBuilder]$builder, [string]$heading, $items) {
  [void]$builder.AppendLine("## $heading")
  [void]$builder.AppendLine()
  foreach ($item in @($items)) { [void]$builder.AppendLine("- $item") }
  [void]$builder.AppendLine()
}

$encoding = [Text.UTF8Encoding]::new($false)
foreach ($id in $boundaryIds) {
  $boundary = $boundaryById[$id]
  $context = $contextById[$id]
  foreach ($field in @('maturity','purpose','owns','non_goals','entrypoints','invariants','verification','references')) {
    if ($null -eq $context.$field -or @($context.$field).Count -eq 0) { throw "$id module context lacks $field" }
  }
  $moduleRoot = Join-Path $root $boundary.root
  if (!(Test-Path -LiteralPath $moduleRoot)) { throw "$id module root is missing: $($boundary.root)" }
  foreach ($entrypoint in @($context.entrypoints)) {
    if (!(Test-Path -LiteralPath (Join-Path $moduleRoot $entrypoint))) { throw "$id entry point is missing: $entrypoint" }
  }
  foreach ($reference in @($context.references)) {
    if (!(Test-Path -LiteralPath (Join-Path $root $reference))) { throw "$id canonical reference is missing: $reference" }
  }
  $upstream = @($boundary.dependencies)
  $downstream = @($boundaries.modules | Where-Object { @($_.dependencies) -contains $id } | ForEach-Object id | Sort-Object)
  $fingerprint = Get-SourceFingerprint $moduleRoot
  $builder = [Text.StringBuilder]::new()
  [void]$builder.AppendLine("# Module: $id")
  [void]$builder.AppendLine()
  [void]$builder.AppendLine('> Generated from `governance/module-context-registry.json` and `governance/module-boundaries.json`. Do not edit this file directly.')
  [void]$builder.AppendLine()
  [void]$builder.AppendLine("- **Maturity:** $($context.maturity)")
  [void]$builder.AppendLine("- **Root:** ``$($boundary.root)``")
  [void]$builder.AppendLine("- **Source fingerprint:** ``$fingerprint``")
  [void]$builder.AppendLine('- **Live project state:** read `context/active/CURRENT_STATE.md`; active status is never duplicated here.')
  [void]$builder.AppendLine()
  [void]$builder.AppendLine('## Purpose')
  [void]$builder.AppendLine()
  [void]$builder.AppendLine($context.purpose)
  [void]$builder.AppendLine()
  Add-List $builder 'Owns' $context.owns
  Add-List $builder 'Does not own' $context.non_goals
  Add-List $builder 'Primary entry points' (@($context.entrypoints) | ForEach-Object { "``$_``" })
  Add-List $builder 'Upstream neighbours' $(if ($upstream.Count) { $upstream } else { @('None declared.') })
  Add-List $builder 'Downstream neighbours' $(if ($downstream.Count) { $downstream } else { @('None declared.') })
  Add-List $builder 'Invariants and failure boundaries' $context.invariants
  Add-List $builder 'Verification' (@($context.verification) | ForEach-Object { "``$_``" })
  Add-List $builder 'Canonical references' (@($context.references) | ForEach-Object { "``$_``" })
  [void]$builder.AppendLine('## Update rule')
  [void]$builder.AppendLine()
  [void]$builder.AppendLine('Read this file before module work. If purpose, ownership, non-goals, interfaces, dependencies, invariants, risks, verification, or canonical references change, update the canonical module-context registry and run `tools\refresh-module-context.ps1`. A source change also changes the fingerprint, so stale projections fail verification.')
  $expected = $builder.ToString().Replace("`r`n", "`n")
  $path = Join-Path $moduleRoot 'MODULE.md'
  if ($Check) {
    if (!(Test-Path -LiteralPath $path) -or (Get-Content -LiteralPath $path -Raw).Replace("`r`n", "`n") -ne $expected) {
      throw "$id MODULE.md is missing, stale, or hand-edited. Run tools\refresh-module-context.ps1 after reviewing canonical context."
    }
  } else {
    [IO.File]::WriteAllText($path, $expected, $encoding)
  }
}
if ($Check) { Write-Output "Module context verified: $($boundaryIds.Count) declared modules have current first-read front doors." }
else { Write-Output "Module context refreshed: $($boundaryIds.Count) MODULE.md front doors generated." }
