$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
. (Join-Path $PSScriptRoot 'g1-c6-successor-route.ps1')
$canonical=Get-Content -Raw (Join-Path $root 'context/active/WORKER_BATCH_STATE.json')|ConvertFrom-Json
if(!(Test-G1C6AuthorizedCurrentRoute -Checkpoint $canonical)){throw 'Canonical C6 route rejected.'}
$readiness=$canonical|ConvertTo-Json -Depth 100|ConvertFrom-Json
$readiness.batch_id='G1-C6-SEMANTIC-CONSTRUCTION-ORGANISM-ECOLOGY-READINESS-V1';$readiness.substage_id='c6-reconciliation-readiness'
$readiness.authority_lane='Owner-authorized C6 semantic/construction and organism-ecology reconciliation and capability-free readiness only. Exact dependencies verified C4 and C5. Retain corrected C6 prerequisite evidence as non-closure evidence. No C6 implementation source, C3B, C7, broad G1 closure, runtime, product ontology or vocabulary, solver or AI generation, geometry, assets, animation, renderer, visual-quality claim, physiology or content constants, filesystem, network, process, Companion, Greenfield, promotion authority or Kernel mutation.'
if(!(Test-G1C6ReconciliationReadinessRoute -Checkpoint $readiness)){throw 'Synthetic C6 readiness route rejected.'}
$implementation=$canonical|ConvertTo-Json -Depth 100|ConvertFrom-Json
$implementation.batch_id='G1-C6-BODY-PLAN-STRUCTURE-IMPLEMENTATION-V1';$implementation.substage_id='c6-body-plan-structure-test-first-implementation'
$implementation.authority_lane='Owner-authorized capability-free C6 body-plan family/topology V1 test-first implementation only. Exact dependencies verified C4 and C5. Authorizes the new body-plan-structure crate, one additive macro-lineage-binding family-reference validator, exact tests, governance projections and verification for this package. No ecology realization, physiology, reproduction, heredity, development, sex or dimorphism applicability, caste, species, individual or population semantics, personhood, product ontology, solver or AI generation, geometry, proportions, pose, assets, animation, renderer, visual-quality claim, runtime, filesystem, network, process, Companion, Greenfield, C7, broad G1 closure, promotion authority or Kernel mutation.'
if(!(Test-G1C6BodyPlanStructureImplementationRoute -Checkpoint $implementation)){throw 'Synthetic C6 body-plan implementation route rejected.'}
$identityReadiness=$canonical|ConvertTo-Json -Depth 100|ConvertFrom-Json
$identityReadiness.batch_id='G1-C6-ORGANISM-IDENTITY-READINESS-V1';$identityReadiness.substage_id='c6-organism-identity-readiness'
$identityReadiness.authority_lane='Owner-routed code-free C6 package-3 identity readiness only. Authorizes reconciliation of stale body-plan projections and design, adversarial review, fixtures, verifier and governance records for distinct lineage, organism-form, species-candidate, individual and population identity envelopes plus exact C4 lifecycle/history consumption. No production crate or source implementation; no asserted species membership, population members/count/distribution, ancestry/evolution inference, ecology, physiology, reproduction, heredity, development, sex, dimorphism, culture, representation, runtime, Companion, Greenfield, C7, promotion authority or Kernel mutation.'
if(!(Test-G1C6OrganismIdentityReadinessRoute -Checkpoint $identityReadiness)){throw 'Synthetic C6 organism identity readiness route rejected.'}
foreach($field in @('batch_id','master_program_item','state','substage_id','authority_lane')){$x=$implementation|ConvertTo-Json -Depth 100|ConvertFrom-Json;$x.$field='FORGED';if(Test-G1C6AuthorizedCurrentRoute -Checkpoint $x){throw "Forged C6 field admitted: $field"}}
Write-Output 'G1 C6 authorized successor routes verified: reconciliation, body-plan implementation and organism identity readiness tuples pass; forged fields fail closed.'
