$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
. (Join-Path $PSScriptRoot 'g1-c6-successor-route.ps1')
$canonical=Get-Content -Raw (Join-Path $root 'context/active/WORKER_BATCH_STATE.json')|ConvertFrom-Json
if(!(Test-G1C6AuthorizedCurrentRoute -Checkpoint $canonical)){throw 'Canonical C6 route rejected.'}
$readiness=$canonical|ConvertTo-Json -Depth 100|ConvertFrom-Json
$readiness.batch_id='G1-C6-SEMANTIC-CONSTRUCTION-ORGANISM-ECOLOGY-READINESS-V1';$readiness.substage_id='c6-reconciliation-readiness'
$readiness.authority_lane='Owner-authorized C6 semantic/construction and organism-ecology reconciliation and capability-free readiness only. Exact dependencies verified C4 and C5. Retain corrected C6 prerequisite evidence as non-closure evidence. No C6 implementation source, C3B, C7, broad G1 closure, runtime, product ontology or vocabulary, solver or AI generation, geometry, assets, animation, renderer, visual-quality claim, physiology or content constants, filesystem, network, process, Companion, Greenfield, promotion authority or Kernel mutation.'
if(!(Test-G1C6ReconciliationReadinessRoute -Checkpoint $readiness)){throw 'Synthetic C6 readiness route rejected.'}
$implementation=$canonical|ConvertTo-Json -Depth 100|ConvertFrom-Json
$implementation.batch_id='G1-C6-BODY-PLAN-STRUCTURE-IMPLEMENTATION-V1';$implementation.substage_id='c6-body-plan-structure-test-first-implementation'
$implementation.authority_lane='Owner-authorized capability-free C6 body-plan family/topology V1 test-first implementation only. Exact dependencies verified C4 and C5. Authorizes the new body-plan-structure crate, one additive macro-lineage-binding family-reference validator, exact tests, governance projections and verification for this package. No ecology realization, physiology, reproduction, heredity, development, sex or dimorphism applicability, caste, species, individual or population semantics, personhood, product ontology, solver or AI generation, geometry, proportions, pose, assets, animation, renderer, visual-quality claim, runtime, filesystem, network, process, Companion, Greenfield, C7, broad G1 closure, promotion authority or Kernel mutation.'
if(!(Test-G1C6BodyPlanStructureImplementationRoute -Checkpoint $implementation)){throw 'Synthetic C6 body-plan implementation route rejected.'}
$identityReadiness=$canonical|ConvertTo-Json -Depth 100|ConvertFrom-Json
$identityReadiness.batch_id='G1-C6-ORGANISM-IDENTITY-READINESS-V1';$identityReadiness.substage_id='c6-organism-identity-readiness'
$identityReadiness.authority_lane='Owner-routed code-free C6 package-3 identity readiness only. Authorizes reconciliation of stale body-plan projections and design, adversarial review, fixtures, verifier and governance records for distinct lineage, organism-form, species-candidate, individual and population identity envelopes plus exact C4 lifecycle/history consumption. No production crate or source implementation; no asserted species membership, population members/count/distribution, ancestry/evolution inference, ecology, physiology, reproduction, heredity, development, sex, dimorphism, culture, representation, runtime, Companion, Greenfield, C7, promotion authority or Kernel mutation.'
if(!(Test-G1C6OrganismIdentityReadinessRoute -Checkpoint $identityReadiness)){throw 'Synthetic C6 organism identity readiness route rejected.'}
$identityImplementation=$canonical|ConvertTo-Json -Depth 100|ConvertFrom-Json
$identityImplementation.batch_id='G1-C6-ORGANISM-SUBJECT-IDENTITY-IMPLEMENTATION-V1';$identityImplementation.substage_id='c6-organism-subject-identity-test-first-implementation'
$identityImplementation.authority_lane='Owner-authorized capability-free C6 organism subject identity V1 test-first implementation only. Exact dependencies verified C4, C5 and body-plan V1. Authorizes the organism-subject-identity crate, one additive person-form-eligibility bound-subject evaluator, exact 33-group implementation matrix, module/governance projections and verification. No asserted species membership, population members/count/distribution, ancestry/evolution inference, ecology, physiology, reproduction, heredity, development, sex, dimorphism, caste, culture, capacity truth, comparison, representation, runtime, filesystem, network, process, Companion, Greenfield, C7, broad G1 closure, promotion authority or Kernel mutation.'
if(!(Test-G1C6OrganismSubjectIdentityImplementationRoute -Checkpoint $identityImplementation)){throw 'Synthetic C6 organism-subject identity implementation route rejected.'}
$ecologyReadiness=$canonical|ConvertTo-Json -Depth 100|ConvertFrom-Json
$ecologyReadiness.batch_id='G1-C6-ECOLOGICAL-NICHE-SEMANTICS-SCHEMA-GAP-AUDIT-V1';$ecologyReadiness.substage_id='c6-ecological-niche-semantics-schema-gap-audit'
$ecologyReadiness.authority_lane='Owner-routed code-free C6 package-4 ecological-niche semantics schema-gap audit only. Authorizes canonical status reconciliation, exact upstream field and authority inventory, claim classification, adversarial source-negative fixtures, verifier and governance records for habitat, resource, hazard, trophic, competition, ecotone and prospective-occupancy prerequisites. No ecological contract schema or production crate/source; no habitat suitability, resource yield, organism hazard, trophic or competition fact, realized occupancy, species or population membership, physiology, viability, senses, locomotion, behavior, reproduction, heredity, development, evolution, dimorphism applicability, comparison, culture, representation, runtime, filesystem, network, process, Companion, Greenfield, C7, broad G1 closure, promotion authority or Kernel mutation.'
if(!(Test-G1C6EcologicalNicheSemanticsSchemaGapRoute -Checkpoint $ecologyReadiness)){throw 'Synthetic C6 ecological-niche schema-gap route rejected.'}
$ecologyDesignReadiness=$canonical|ConvertTo-Json -Depth 100|ConvertFrom-Json
$ecologyDesignReadiness.batch_id='G1-C6-ECOLOGICAL-NICHE-SEMANTICS-DESIGN-READINESS-V1';$ecologyDesignReadiness.substage_id='c6-ecological-niche-semantics-design-readiness'
$ecologyDesignReadiness.authority_lane='Owner-routed code-free C6 package-4 ecological-niche semantics authored-hypothesis design and implementation-readiness only. Authorizes one mathematical-design audit, one capability-free strict contract candidate, one implementation-readiness record, disposable document/route hostile fixtures, verifier and canonical governance reconciliation for provenance-bound prospective habitat, resource, hazard, trophic, competition, ecotone and occupancy candidate assertions with typed necessary-evidence-supported, unavailable, contradictory and budget-indeterminate validation outcomes. No production crate or source, Cargo member or dependency, consumer implementation, ecological truth, habitat suitability, resource accessibility/yield/replenishment, organism-specific harm, trophic flow, competition fact, production ecotone, realized occupancy, species or population membership, physiology, viability, senses, locomotion, behavior, reproduction, heredity, development, evolution, sex or dimorphism applicability, comparison, culture, representation, runtime, filesystem, network, process, database, UI, renderer, Companion, Greenfield, C7, broad G1 closure, promotion authority or Kernel mutation.'
if(!(Test-G1C6EcologicalNicheSemanticsDesignReadinessRoute -Checkpoint $ecologyDesignReadiness)){throw 'Synthetic C6 ecological-niche semantics design/readiness route rejected.'}
foreach($field in @('batch_id','master_program_item','state','substage_id','authority_lane')){$x=$implementation|ConvertTo-Json -Depth 100|ConvertFrom-Json;$x.$field='FORGED';if(Test-G1C6AuthorizedCurrentRoute -Checkpoint $x){throw "Forged C6 field admitted: $field"}}
foreach($field in @('batch_id','master_program_item','state','substage_id','authority_lane')){$x=$ecologyReadiness|ConvertTo-Json -Depth 100|ConvertFrom-Json;$x.$field='FORGED';if(Test-G1C6AuthorizedCurrentRoute -Checkpoint $x){throw "Forged C6 ecology field admitted: $field"}}
foreach($field in @('batch_id','master_program_item','state','substage_id','authority_lane')){$x=$ecologyDesignReadiness|ConvertTo-Json -Depth 100|ConvertFrom-Json;$x.$field='FORGED';if(Test-G1C6AuthorizedCurrentRoute -Checkpoint $x){throw "Forged C6 ecology design/readiness field admitted: $field"}}
Write-Output 'G1 C6 authorized successor routes verified: reconciliation, body-plan implementation, organism identity readiness, organism-subject identity implementation, ecological-niche schema-gap and authored-hypothesis design/readiness tuples pass; forged fields fail closed.'
