Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$audit = Get-Content -LiteralPath (Join-Path $root 'docs\canonical-system\G1_C3_POST_CUMULATIVE_LANE_TRANSFER_CONSUMER_REASSESSMENT.md') -Raw
$result = Get-Content -LiteralPath (Join-Path $root 'docs\canonical-system\G1_C3_CUMULATIVE_LANE_TRANSFER_IMPLEMENTATION_RESULT.md') -Raw
$program = Get-Content -LiteralPath (Join-Path $root 'docs\canonical-system\MASTER_PROGRAM.json') -Raw | ConvertFrom-Json
$checkpoint = Get-Content -LiteralPath (Join-Path $root 'context\active\WORKER_BATCH_STATE.json') -Raw | ConvertFrom-Json
foreach ($required in @('dimensionless followed-lane transfer prerequisite is verified','receiver arrival, source emission/spreading','detector response remain','receiver-arrival geometry mathematical audit','source-emission and geometric-spreading owner','receiver-arrival geometry owner','combined source-to-detector record','geometry comes before source magnitude','tangent contact versus strict interior entry','receiver crossing a cell boundary','interval direction boxes','exact rational reference','Do not add a crate')) {
  if ($audit -notlike "*$required*") { throw "Post-cumulative reassessment drift: $required" }
}
if ($result -notlike '*implemented and verified*' -or $result -notlike '*234.0 seconds*') {
  throw 'Verified cumulative implementation result is not retained.'
}
$c3 = @($program.items | Where-Object id -eq 'C3')
$federatedContinuity = $c3.Count -eq 1 -and (& (Join-Path $PSScriptRoot 'test-c3-federated-interruption.ps1') -Checkpoint $checkpoint -C3 $c3[0])
$designRoute = $c3.Count -eq 1 -and $c3[0].next_action -like '*code-free receiver-arrival geometry mathematical design*counterexample/oracle audit*' -and $c3[0].next_action -like '*Do not add a crate*schema*source*'
$ownerRoute = $c3.Count -eq 1 -and $c3[0].next_action -like '*G1_C3_RECEIVER_ARRIVAL_GEOMETRY_IMPLEMENTATION_READINESS.md*explicit owner approval*'
$implementationRoute = $c3.Count -eq 1 -and $c3[0].next_action -like '*approved*G1_C3_RECEIVER_ARRIVAL_GEOMETRY_IMPLEMENTATION_READINESS.md*receiver-arrival-geometry-binding*'
$downstreamRoute = $c3.Count -eq 1 -and $c3[0].next_action -like '*optical phase-space provenance prerequisite*'
$sourceQuantityRoute = $c3.Count -eq 1 -and ($c3[0].next_action -like '*calibrated spectral/time basis mathematical design audit*' -or $c3[0].next_action -like '*calibrated-basis*transport-applicability schema gap audit*' -or $c3[0].next_action -like '*implementation-readiness audit*source-calibration sibling*' -or $c3[0].next_action -like '*calibrated source-energy distribution ownership*implementation-readiness audit*' -or $c3[0].next_action -like '*explicit owner decision*calibrated-source-energy-distribution*' -or $c3[0].next_action -like '*owner-approved bounded calibrated-source-energy-distribution*')
if (-not ($designRoute -or $ownerRoute -or $implementationRoute -or $downstreamRoute -or $sourceQuantityRoute -or $federatedContinuity) -or
    ($c3[0].proof -notlike '*cumulative transfer owner remains implemented and verified*' -and $c3[0].proof -notlike '*cumulative transfer and receiver-arrival owners remain implemented*' -and $c3[0].proof -notlike '*exact-lineage cumulative transfer*complete-cell result*' -and $c3[0].proof -notlike '*whole-cell dimensionless-transfer result*source-distribution*' -and $c3[0].proof -notlike '*source-quantity basis mathematical design*integrated radiant energy*' -and $c3[0].proof -notlike '*calibrated spectral/time mathematical design*pointwise*' -and $c3[0].proof -notlike '*calibrated-basis and transport-applicability*stateless derived commitment*' -and $c3[0].proof -notlike '*closed-frontier additive calibrated radiant-energy measure*Transport applicability remains blocked*' -and $c3[0].proof -notlike '*compact axis-bearing*zero downstream consumers*' -and $c3[0].proof -notlike '*owner explicitly approved*zero downstream consumers*' -and $c3[0].proof -notlike '*scale ambiguity*spectral/time ambiguity*separate capability-free applicability sibling*')) {
  throw 'C3 does not retain the selected receiver-arrival geometry design route.'
}
$designCheckpoint = $checkpoint.batch_id -eq 'G1-C3-RECEIVER-ARRIVAL-GEOMETRY-MATHEMATICAL-DESIGN-V1' -and $checkpoint.substage_id -eq 'receiver-arrival-geometry-mathematical-design' -and $checkpoint.authority_lane -like '*Mathematical design and independent oracle only*No crate*schema*source*no emission*visibility*perception*runtime*promotion*C3 closure*'
$ownerCheckpoint = $checkpoint.batch_id -eq 'G1-C3-RECEIVER-ARRIVAL-GEOMETRY-IMPLEMENTATION-READINESS-V1' -and $checkpoint.substage_id -eq 'receiver-arrival-geometry-owner-gate' -and $checkpoint.authority_lane -like '*requires explicit owner approval*No crate*schema*source*visibility*C3 closure*'
$implementationCheckpoint = $checkpoint.batch_id -eq 'G1-C3-RECEIVER-ARRIVAL-GEOMETRY-IMPLEMENTATION-V1' -and $checkpoint.substage_id -in @('receiver-arrival-geometry-additive-source-implementation','receiver-arrival-geometry-post-result-consumer-reassessment') -and $checkpoint.authority_lane -like '*explicitly approved*receiver-arrival*visibility*perception*runtime*promotion*C3 closure*'
$laterReadiness = $checkpoint.batch_id -eq 'G1-C3-RECEIVER-ARRIVAL-GEOMETRY-IMPLEMENTATION-V1' -and $checkpoint.substage_id -in @('optical-phase-space-cell-provenance-implementation-readiness','optical-phase-space-cell-provenance-owner-gate') -and $checkpoint.authority_lane -like '*Readiness audit only and explicit owner gate*Existing owners remain unchanged*visibility*runtime*promotion*C3 closure*'
$laterImplementation = $checkpoint.batch_id -eq 'G1-C3-RECEIVER-ARRIVAL-GEOMETRY-IMPLEMENTATION-V1' -and $checkpoint.substage_id -in @('optical-phase-space-cell-provenance-additive-source-implementation','optical-phase-space-cell-provenance-post-result-consumer-reassessment','optical-phase-space-transport-certificate-design-and-oracle','optical-phase-space-transport-certificate-arithmetic-width-spike','optical-phase-space-transport-origin-anchored-design-and-oracle','optical-phase-space-transport-origin-anchored-implementation-readiness','optical-phase-space-transport-origin-anchored-owner-gate') -and $checkpoint.authority_lane -like '*Owner-approved exact additive package*Existing owner source and behavior remain unchanged*visibility*runtime*promotion*C3 closure*'
$transportImplementation = $checkpoint.batch_id -eq 'G1-C3-RECEIVER-ARRIVAL-GEOMETRY-IMPLEMENTATION-V1' -and $checkpoint.substage_id -in @('optical-phase-space-transport-origin-anchored-implementation','optical-phase-space-transport-origin-anchored-verification','optical-phase-space-transport-origin-anchored-result') -and $checkpoint.authority_lane -like '*Owner-authorized implementation*optical-phase-space-transport-certificate*no arrival*visibility*runtime*promotion*C3-closure authority*'
$sourceQuantityCheckpoint = $checkpoint.batch_id -eq 'G1-C3-SOURCE-QUANTITY-BASIS-MATHEMATICAL-DESIGN-V1' -and $checkpoint.substage_id -eq 'source-quantity-basis-oracle-result' -and $checkpoint.authority_lane -like '*Code-free mathematical design and deterministic exact-rational oracle only*No crate*contract schema*production source*RGB boundaries*tick duration*visibility*runtime*promotion*C3 closure*'
if (-not ($designCheckpoint -or $ownerCheckpoint -or $implementationCheckpoint -or $laterReadiness -or $laterImplementation -or $transportImplementation -or $sourceQuantityCheckpoint -or $federatedContinuity)) {
  throw 'Receiver-arrival geometry mathematical checkpoint or authority boundary drifted.'
}
Write-Output 'Post-cumulative reassessment verified: the dimensionless fold is retained, receiver geometry is selected as a separate code-free seam, and source, detector, visibility and authority claims remain excluded.'
