param([string]$ReceiptPath,[Parameter(Mandatory=$true)][string]$SemanticSha256,[Parameter(Mandatory=$true)][string]$BoundedSourceManifestSha256)
$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;if([string]::IsNullOrWhiteSpace($ReceiptPath)){$ReceiptPath=Join-Path $root 'docs\canonical-system\G1_C4_LOCAL_PLATFORM_OBSERVATIONS.json'}
if(!(Test-Path -LiteralPath $ReceiptPath -PathType Leaf)){throw 'C4 retained platform observation receipt is missing.'};$r=Get-Content -Raw $ReceiptPath|ConvertFrom-Json
if($r.schema_version-ne1-or$r.receipt_id-ne'G1-C4-LOCAL-PLATFORM-OBSERVATIONS'-or$r.semantic_receipt_sha256-ne$SemanticSha256-or$r.bounded_source_manifest_sha256-ne$BoundedSourceManifestSha256-or$r.independent_second_platform_execution-ne$false-or$r.promotion_authority-ne$false){throw 'C4 platform receipt root binding changed.'}
if($r.source_commit-notmatch'^[0-9a-f]{40}$'-or$r.tracked_tree_manifest_sha256-notmatch'^[0-9a-f]{64}$'){throw 'C4 platform source provenance is malformed.'};git cat-file -e "$($r.source_commit)^{commit}";if($LASTEXITCODE-ne0){throw 'C4 platform source commit is unavailable.'}
$tree=((git ls-tree -r --full-tree $r.source_commit|Out-String).TrimEnd());$sha=[Security.Cryptography.SHA256]::Create();try{$actual=([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($tree))).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()};if($actual-ne$r.tracked_tree_manifest_sha256){throw 'C4 tracked-tree manifest binding changed.'}
if([string]::IsNullOrWhiteSpace($r.rustc)-or[string]::IsNullOrWhiteSpace($r.cargo)-or@($r.observations).Count-ne3){throw 'C4 platform toolchain or observation count is missing.'}
$native=$r.observations[0];$i686=$r.observations[1];$android=$r.observations[2]
if($native.classification-ne'native_same_host_execution'-or$native.target-ne'x86_64-pc-windows-msvc'-or$native.pointer_width-ne64-or$native.endian-ne'little'-or$native.exit_code-ne0-or@($native.process_ids|Select-Object -Unique).Count-ne2-or@($native.stdout_sha256).Count-ne2-or@($native.stdout_sha256|Select-Object -Unique).Count-ne1-or@($native.stderr_sha256).Count-ne2-or!$native.executable.present-or$native.executable.sha256-notmatch'^[0-9a-f]{64}$'-or[string]::IsNullOrWhiteSpace($native.command)){throw 'C4 native platform observation is invalid.'}
if($i686.classification-ne'same_host_second_architecture'-or$i686.target-ne'i686-pc-windows-msvc'-or$i686.pointer_width-ne32-or$i686.exit_code-ne0-or@($i686.process_ids).Count-ne1-or@($i686.stdout_sha256).Count-ne1-or$i686.stdout_sha256[0]-ne$native.stdout_sha256[0]-or@($i686.stderr_sha256).Count-ne1-or!$i686.executable.present-or$i686.executable.sha256-notmatch'^[0-9a-f]{64}$'-or[string]::IsNullOrWhiteSpace($i686.command)){throw 'C4 i686 observation is invalid.'}
if($android.classification-ne'compile_only'-or$android.target-ne'aarch64-linux-android'-or$android.pointer_width-ne64-or$android.exit_code-ne0-or@($android.process_ids).Count-ne1-or@($android.stdout_sha256).Count-ne1-or@($android.stderr_sha256).Count-ne1-or$android.executable.present-or[string]::IsNullOrWhiteSpace($android.executable.reason)-or[string]::IsNullOrWhiteSpace($android.command)){throw 'C4 Android compile-only observation is invalid.'}
Write-Output "C4 retained platform observations verified: commit $($r.source_commit), semantic $SemanticSha256, no independent execution."
